channels:
  - conda-forge

dependencies:
  - python=3.9.0             
  - pip=20.2.3                    
  - pip:
    - rpaframework==28.6.0
    - pandas==2.2.2
    - selenium==4.15.2
    - geckodriver-autoinstaller==0.1.0