channels:
  - conda-forge

dependencies:
  - python=3.9.0             
  - pip=20.2.3 
  - firefox=127.0.1            
  - pip:
    - rpaframework==28.6.0
    - pandas==2.2.2
    - get-gecko-driver==1.3.13